name: checkgasusage
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.16.1
  rect_getter: ^0.1.0
  kopo: ^0.1.1


  firebase_core: ^0.5.2
  firebase_auth: ^0.18.3
  cloud_firestore: ^0.14.4
  camera: ^0.6.2+1
  firebase_ml_vision: ^0.9.10
  image_picker: ^0.6.7+17
  path_provider: ^1.6.24
  kakao_flutter_sdk: ^0.5.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icon/7.png
    - assets/icon/8712.png
    - assets/icon/back.png
    - assets/icon/pen.png
    - assets/icon/pen_small.png
    - assets/icon/search_glyph.png
    - assets/icon/x.png
    - assets/image/auth_page/123.png
    - assets/image/auth_page/5733.png
    - assets/image/auth_page/6378.png
    - assets/image/auth_page/kakao_talk.png
    - assets/image/bnb_items/home.png
    - assets/image/bnb_items/my_usage.png
    - assets/image/bnb_items/setting.png
    - assets/image/bnb_items/setting.png
    - assets/image/setting_page/6383.png
    - assets/image/setting_page/6384.png
    - assets/image/setting_page/6387.png
    - assets/image/setting_page/6388.png
    - assets/image/setting_page/6389.png
    - assets/image/setting_page/8739.png
    - assets/image/register_info/gas_pipe.png
    - assets/logo/gas.png

  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSansCJKkr/NotoSansCJKkr-Light.otf
          weight: 200
        - asset: fonts/NotoSansCJKkr/NotoSansCJKkr-Regular.otf
          weight: 400
        - asset: fonts/NotoSansCJKkr/NotoSansCJKkr-Medium.otf
          weight: 500
        - asset: fonts/NotoSansCJKkr/NotoSansCJKkr-Bold.otf
          weight: 700

    - family: AppleSDGothicNeo
      fonts:
        - asset: fonts/AppleSDGothicNeo/AppleSDGothicNeoR.ttf
          weight: 400
        - asset: fonts/AppleSDGothicNeo/AppleSDGothicNeoM.ttf
          weight: 500
        - asset: fonts/AppleSDGothicNeo/AppleSDGothicNeoB.ttf
          weight: 700


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
